### ISSUE TITLE
SPARK MAX Cannot Connect

### ISSUE THREAD

**Issue by DarthWunka** [REVrobotics/SPARK-MAX-Client#77]
**Describe the bug**
This issue occurs whenever we try to connect to a spark max, it will show it as an option and as soon as you hit connect it says syncing and then it disappears 

**To Reproduce**
1. Plug-In a Spark Max
2. Wait for it to show as an option
3. Click Connect
4. Watch the spot where the name would show

**Expected behavior**
I would expect to be able to connect to the controller and change settings

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SPARK MAX Client Version 2.0.0

**Additional context**
N/A

**Comment by OfekHarel** [comment]
Having the same issue...
Any updates?

**Comment by DarthWunka** [comment]
It would appear that updating to 2.1.0 fixed it

**Comment by willtoth** [comment]
There are a few other tweaks in the works that will further improve this issue.

**Comment by DarthWunka** [comment]
Okay cool
